### ISSUE TITLE
setup.py file execution raises an error during python package installation with Jfrog rt pip-install

### ISSUE THREAD

**Issue by usinelogicielle** [jfrog/jfrog-cli#1376]
**Describe the bug**
We are performing our Continuous Integration on Jenkins and we installed the Jfrog client on our agents (version 1.44).
When we install a python package with Jfrog-cli, the client tries to execute the Setup.py file located at the root folder of the project and that raises an error in our jobs. Is this a bug?
How can download packages without the setup.py file being executed?
Are we using properly jfrog-cli? 
If we indicate the modul name with "jfrog rt pip-install --no-cache-dir --force-reinstall requests --module=module-name" it works. Is it the right usage (specify the module name ti pipi)? 

**Expected behavior**
The package installation should complete without having to move the setup.py file from the project root to another folder.

**Screenshots**
Here is the project tree:
 ______Jenkinsfile
|
|______setup.py

Here are the steps to download the python packages in the Jenkinsfile. We instantiate a server and we update the version of pip.Tthen we install the “requests” package.

![image](https://user-images.githubusercontent.com/73827301/149167536-8f4ce291-e493-4e01-a5ea-e5c2541ead46.png)

Here are the logs we get when launching the Jenkins job. We created an error in the setup.py file to show that it is executed when downloading the packages. If the error appears in the logs that means the setup.py is executed by the jfrog-cli client. And this is what happens. 

2022-01-12 14:11:09  + jfrog rt pip-install --no-cache-dir --force-reinstall requests
2022-01-12 14:11:09  [Info] Running pip Install.
2022-01-12 14:11:10  Looking in indexes: https://****:****@artifactoryURL
2022-01-12 14:11:10  Collecting requests
2022-01-12 14:11:10    Downloading https://artifactoryURL/requests-2.27.1-py2.py3-none-any.whl (63 kB)
2022-01-12 14:11:10  Collecting idna<4,>=2.5
2022-01-12 14:11:10    Downloading https://artifactoryURL/idna-3.3-py3-none-any.whl (61 kB)
2022-01-12 14:11:10  Collecting charset-normalizer~=2.0.0
2022-01-12 14:11:10    Downloading https://artifactoryURL/charset_normalizer-2.0.10-py3-none-any.whl (39 kB)
2022-01-12 14:11:11  Collecting certifi>=2017.4.17
2022-01-12 14:11:11    Downloading https://artifactoryURL/certifi-2021.10.8-py2.py3-none-any.whl (149 kB)
2022-01-12 14:11:11  Collecting urllib3<1.27,>=1.21.1
2022-01-12 14:11:11    Downloading https://artifactoryURL/urllib3-1.26.8-py2.py3-none-any.whl (138 kB)
2022-01-12 14:11:11  Installing collected packages: urllib3, idna, charset-normalizer, certifi, requests
2022-01-12 14:11:11  Successfully installed certifi-2021.10.8 charset-normalizer-2.0.10 idna-3.3 requests-2.27.1 urllib3-1.26.8
2022-01-12 14:11:12  Traceback (most recent call last):
2022-01-12 14:11:12    File "/srv/jenkins/workspace/usinelogicielle/private/sandbox/Test-TP-Atrifactory/setup.py", line 14, in <module>
2022-01-12 14:11:12      name=set_name("tp-artifactory"), # Nom sous lequel le package sera distribué
2022-01-12 14:11:12    File "/srv/jenkins/workspace/usinelogicielle/private/sandbox/Test-TP-Atrifactory/setup.py", line 8, in set_name
2022-01-12 14:11:12      raise ValueError('JFROG-CLI execute setup.py')
2022-01-12 14:11:12  ValueError: JFROG-CLI execute setup.py
2022-01-12 14:11:12  [Error] Failed determining module-name from 'setup.py' file: exit status 1

Here is the content of setup.py.

![image](https://user-images.githubusercontent.com/73827301/149167677-98de5b8e-8b01-447b-9532-48620af253dd.png)

Thanks in advance for your help :)

**Comment by sverdlov93** [comment]
Hi @usinelogicielle,
Thanks for reporting this issue.
Our apologies for the inconvenience caused by this bug.
We believe that the issue was fixed on jfrog-cli - 2.10.0, so feel free to update the cli version to the latest.
Also, the same fix should be released for jfrog-cli V1 soon. (jfrog-cli-core PR) [https://github.com/jfrog/jfrog-cli-core/pull/283].

Looking forward to your feedback on it.

**Comment by sverdlov93** [comment]
Hi @usinelogicielle,
JFrog CLI 1.53.0 is released and should fix the above issue.
Looking forward to your feedback on it.

**Comment by usinelogicielle** [comment]
Hello, 

Thanks for your reply, I will test the new version and give you my feed back as soon as possible :)

**Comment by usinelogicielle** [comment]
With JFrog CLI 1.53.0 (V1) the issue is fixed.
Thank you !
