### ISSUE TITLE
Full docker image contains incompatible Yarn version

### ISSUE THREAD

**Issue by lqc** [jfrog/jfrog-cli#1397]
**Describe the bug**
The Yarn bundled with the "full" version of CLI is v1.22.11 while 2.4+ is required.

**To Reproduce**
Run 
```
$ docker run --rm -it releases-docker.jfrog.io/jfrog/jfrog-cli-full-v2-jf:e3414e38b41b yarn -v
1.22.11
```

**Expected behavior**
A yarn version that works with CLI is bundled.

**Screenshots**

**Versions**
- JFrog CLI version: e3414e38b41b (2.11.0
- JFrog CLI operating system: Docker

**Comment by asafgabai** [comment]
Hi @lqc, thanks for your report. Yarn v2 (and v3) cannot be installed globally but on a specific project, so the image contains Yarn v1 (globally), and you can use it to initialize Yarn v2 in your project and then execute Yarn commands with JFrog CLI.
You can also initialize Yarn v2 in your project outside of the container and then use it inside the container.
You can read more about initializing Yarn in your project and migrating to Yarn in Yarn's documentation: https://yarnpkg.com/getting-started/install
Let me know if you have any questions or suggestions.

**Comment by lqc** [comment]
It actually can be installed globally, but you are right the recommended setup is to check in the yarn bundle to the project. Did exactly that and it still doesn't work:

```
$ docker run --rm -it  \
  -v $(pwd):/home/frogger/app \
  -v $HOME/.jfrog:/home/frogger/.jfrog \
  -w /home/frogger/app \
  releases-docker.jfrog.io/jfrog/jfrog-cli-full-v2-jf \
  jf yarn install

[Info] Running Yarn...
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'worker_threads'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at /home/frogger/app/.yarn/releases/yarn-3.1.1.cjs:426:2642
    at Object.<anonymous> (/home/frogger/app/.yarn/releases/yarn-3.1.1.cjs:723:7786)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
exit status 1
```

It seems that's because the Node version is the image is 10.15 which has already reached EOL.

**Comment by asafgabai** [comment]
@lqc You're right. Fortunately, a few days ago [we upgraded](https://github.com/jfrog/jfrog-ecosystem-integration-env/pull/16) the Node version to 16. I'll update here when it's released.

**Comment by asafgabai** [comment]
@lqc JFrog CLI v2.12.0 was released, and its full image contains Node v16. Let me know if it works for you.
