### ISSUE TITLE
jf npm install command throws 401 error message.

### ISSUE THREAD

**Issue by manojkumarm-git** [jfrog/jfrog-cli#1844]
### Describe the bug

jf npm install fails with “npm ERR! code E401” error even if configured with valid tokens.

Configured the .npmrc file and npm registry with CLI and configured the dependency repo using “jf npm-config” commands.

`C:\Users\manojkumarm>jf npm install mocha
06:32:00 [Info] Running npm install.
npm ERR! code E401
npm ERR! Incorrect or missing password.
npm ERR! If you were trying to login, change your password, create an
npm ERR! authentication token or enable two-factor authentication then
npm ERR! that means you likely typed your password in incorrectly.
npm ERR! Please try again, or recover your password at:
npm ERR!     https://www.npmjs.com/forgot
npm ERR!
npm ERR! If you were doing some other operation then your saved credentials are
npm ERR! probably out of date. To correct this please try logging in again with:
npm ERR!     npm login
{
  "error": {
    "code": "E401",
    "summary": "Incorrect or missing password.",
    "detail": "If you were trying to login, change your password, create an\nauthentication token or enable two-factor authentication then\nthat means you likely typed your password in incorrectly.\nPlease try again, or recover your password at:\n    https://www.npmjs.com/forgot\n\nIf you were doing some other operation then your saved credentials are\nprobably out of date. To correct this please try logging in again with:\n    npm login"
  }
}`

But the same working with normal “npm install” commands.

`C:\Users\manojkumarm>jf npm install danger
06:26:59 [Info] Running npm install.
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
{
  "added": 130,
  "removed": 0,
  "changed": 0,
  "audited": 377,
  "funding": 0,
  "audit": {
    "vulnerabilities": {
      "info": 0,
      "low": 0,
      "moderate": 0,
      "high": 0,
      "critical": 0,
      "total": 0
    },
    "dependencies": {
      "prod": 376,
      "dev": 0,
      "optional": 1,
      "peer": 0,
      "peerOptional": 0,
      "total": 376
    }
  }
}
06:27:49 [Info] npm install finished successfully.
`

### Current behavior

jf npm install fails with the “npm ERR! code E401” error.

Configured the .npmrc file and npm registry with CLI and configured the dependency repo using “jf npm-config” commands.

`C:\Users\manojkumarm>jf npm install mocha
06:32:00 [Info] Running npm install.
npm ERR! code E401
npm ERR! Incorrect or missing password.
npm ERR! If you were trying to login, change your password, create an
npm ERR! authentication token or enable two-factor authentication then
npm ERR! that means you likely typed your password in incorrectly.
npm ERR! Please try again, or recover your password at:
npm ERR!     https://www.npmjs.com/forgot
npm ERR!
npm ERR! If you were doing some other operation then your saved credentials are
npm ERR! probably out of date. To correct this please try logging in again with:
npm ERR!     npm login
{
  "error": {
    "code": "E401",
    "summary": "Incorrect or missing password.",
    "detail": "If you were trying to login, change your password, create an\nauthentication token or enable two-factor authentication then\nthat means you likely typed your password in incorrectly.\nPlease try again, or recover your password at:\n    https://www.npmjs.com/forgot\n\nIf you were doing some other operation then your saved credentials are\nprobably out of date. To correct this please try logging in again with:\n    npm login"
  }
}`

But the same working with normal “npm install” commands.

`C:\Users\manojkumarm>jf npm install danger
06:26:59 [Info] Running npm install.
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
{
  "added": 130,
  "removed": 0,
  "changed": 0,
  "audited": 377,
  "funding": 0,
  "audit": {
    "vulnerabilities": {
      "info": 0,
      "low": 0,
      "moderate": 0,
      "high": 0,
      "critical": 0,
      "total": 0
    },
    "dependencies": {
      "prod": 376,
      "dev": 0,
      "optional": 1,
      "peer": 0,
      "peerOptional": 0,
      "total": 376
    }
  }
}
06:27:49 [Info] npm install finished successfully.
`
the 

### Reproduction steps

1. Configured Art instance with CLI “jf c add” and tested the connection.
2. Configured the npm repo using “jf npm-config”
3. Configured the npm registry using “jf npm config set registry”.
4. Run “jf npm login” and it will show a link and via the link logged in to Artifactory.
5. Run “jf npm install” which will throw an error “E401”.From the debug logs it shows “ verbose stack HttpErrorAuthUnknown: Unable to authenticate, need: Basic realm="Artifactory Realm"
6. The same token working with normal “npm install”
7. Downgraded the node version to 18.0.0 and below both “jf npm install” and “npm install” working fine.
8. Tested with 18.14.0, 18.14.1 and latest 19.17.0 etc. The "jf npm install" throws a 401 error.

`C:\Users\manojkumarm>jf --version
jf version 2.34.2

C:\Users\manojkumarm>node --version
v18.14.0

C:\Users\manojkumarm>npm --version
10.3.1
`

### Expected behavior

The “jf npm install” should work with valid tokens and shouldn’t throw 401 errors.

### JFrog CLI version

2.34.2

### Operating system type and version

Windows, Mac and Linux

### JFrog Artifactory version

NA

### JFrog Xray version

NA

**Comment by omerzi** [comment]
Hey @manojkumarm-git, thanks for reporting this issue; we are aware of it and working on it. For now, you can add this field to your `.npmrc` instead of the `_auth` field:

`//<server-url>/artifactory/api/npm/<npm_remote_repo_name>:_auth = "<npm_auth_token>"`

To generate the npm_auth_token:

`curl -u <username>:<access_token> https://<server-url>/artifactory/api/npm/auth/`

Let me know if it works for you.

**Comment by manojkumarm-git** [comment]
Hi @omerzi , I tried the above configuration and got the same 401 output from "jf npm install".

**Comment by omerzi** [comment]
Hey @manojkumarm-git, I opened a PR with a fix:
https://github.com/jfrog/jfrog-cli-core/pull/695
Once it's approved and released I'll let you know.

**Comment by rvodden** [comment]
This is blocking all our releases too. @omerzi  I've raised 238557 with support, hopefully that will help you get this merged quicker.

**Comment by usinelogicielle** [comment]
Hi @manojkumarm-git 

Which version is the artifactory?
The change of auth in NPM is very recent. So the curl command can not working.

**Comment by manojkumarm-git** [comment]
Hi @usinelogicielle ,

I have tested on Artifactory version 7.53.3.

**Comment by yahavi** [comment]
Thanks for reporting this issue - @rvodden, @usinelogicielle & @manojkumarm-git!
We think that the root causes are two breaking changes introduced somewhere in npm 9.3.
We are also aware of the urgency and are working to deliver a fix quickly, with thoughts about keeping supporting old npm versions.

We'll keep you posted.

**Comment by omerzi** [comment]
Hey @rvodden @usinelogicielle  @manojkumarm-git, [JFrog CLI v2.34.5](https://github.com/jfrog/jfrog-cli/releases/tag/v2.34.5) has been released with a fix. I would appreciate it if you could let me know if it work for you. Thanks!

**Comment by rvodden** [comment]
@omerzi I am still seeing a build failure, but I'm yet to establish if this is owing to `jf cli` or something unrelated - the error message has certainly changed, so we're definitely making progress! What I'm seeing now is:

definitely on the latest `jf cli`:

```
Run jfrog/setup-jfrog-cli@v3
Setup JFrog CLI
  Downloading JFrog CLI from https://releases.jfrog.io/artifactory/jfrog-cli/v2/2.34.5/jfrog-cli-linux-amd64/jfrog
  /opt/hostedtoolcache/jf/2.34.5/x64/jf config add setup-jfrog-cli-server --url https://humanisingautonomy.jfrog.io/ --access-token ***
```

results in this error:

```
Run jf npm ci --legacy-peer-deps
  jf npm ci --legacy-peer-deps
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    JFROG_CLI_ENV_EXCLUDE: *password*;*secret*;*key*;*token*;*auth*;JF_ARTIFACTORY_*;JF_ENV_*;JF_URL;JF_USER;JF_PASSWORD;JF_ACCESS_TOKEN
    JFROG_CLI_OFFER_CONFIG: false
    JFROG_CLI_BUILD_NAME: Testing upload_test_results_to_xray
    JFROG_CLI_BUILD_NUMBER: 147
    JFROG_CLI_BUILD_URL: https://github.com/HumanisingAutonomy/ha-foundation-github-actions/actions/runs/4[2](https://github.com/HumanisingAutonomy/ha-foundation-github-actions/actions/runs/4282157675/jobs/7456077569#step:5:2)82157675
    JFROG_CLI_USER_AGENT: setup-jfrog-cli-github-action/[3](https://github.com/HumanisingAutonomy/ha-foundation-github-actions/actions/runs/4282157675/jobs/7456077569#step:5:3).0.0
12:05:59 [Info] Running npm ci.
npm WARN deprecated @octokit/webhooks-definitions@3.67.3: Use @octokit/webhooks-types, @octokit/webhooks-schemas, or @octokit/webhooks-examples instead. See https://github.com/octokit/webhooks/issues/[4](https://github.com/HumanisingAutonomy/ha-foundation-github-actions/actions/runs/4282157675/jobs/7456077569#step:5:4)47

> upload_test_results_to_xray@0.0.0 prepare
> mkdir -p dist && cp -r src/queries dist && ncc build --source-map --license licenses.txt

ncc: Version 0.31.1
ncc: Compiling file index.js into CJS
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at hashOf (/home/runner/work/ha-foundation-github-actions/ha-foundation-github-actions/upload_test_results_to_xray/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:37:18[5](https://github.com/HumanisingAutonomy/ha-foundation-github-actions/actions/runs/4282157675/jobs/7456077569#step:5:5)5992)
    at ncc (/home/runner/work/ha-foundation-github-actions/ha-foundation-github-actions/upload_test_results_to_xray/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:37:18[6](https://github.com/HumanisingAutonomy/ha-foundation-github-actions/actions/runs/4282157675/jobs/7456077569#step:5:6)045[7](https://github.com/HumanisingAutonomy/ha-foundation-github-actions/actions/runs/4282157675/jobs/7456077569#step:5:7))
    at runCmd (/home/runner/work/ha-foundation-github-actions/ha-foundation-github-actions/upload_test_results_to_xray/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:5512[8](https://github.com/HumanisingAutonomy/ha-foundation-github-actions/actions/runs/4282157675/jobs/7456077569#step:5:8))
    at 81[9](https://github.com/HumanisingAutonomy/ha-foundation-github-actions/actions/runs/4282157675/jobs/7456077569#step:5:9) (/home/runner/work/ha-foundation-github-actions/ha-foundation-github-actions/upload_test_results_to_xray/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:5[16](https://github.com/HumanisingAutonomy/ha-foundation-github-actions/actions/runs/4282157675/jobs/7456077569#step:5:17)98)
    at __webpack_require__ (/home/runner/work/ha-foundation-github-actions/ha-foundation-github-actions/upload_test_results_to_xray/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:59048)
    at /home/runner/work/ha-foundation-github-actions/ha-foundation-github-actions/upload_test_results_to_xray/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:59260
    at /home/runner/work/ha-foundation-github-actions/ha-foundation-github-actions/upload_test_results_to_xray/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:593[21](https://github.com/HumanisingAutonomy/ha-foundation-github-actions/actions/runs/4282157675/jobs/7456077569#step:5:22)
    at Object.<anonymous> (/home/runner/work/ha-foundation-github-actions/ha-foundation-github-actions/upload_test_results_to_xray/node_modules/@vercel/ncc/dist/ncc/cli.js:8:[28](https://github.com/HumanisingAutonomy/ha-foundation-github-actions/actions/runs/4282157675/jobs/7456077569#step:5:29)) {
  opensslErrorStack: [ 'error:0[30](https://github.com/HumanisingAutonomy/ha-foundation-github-actions/actions/runs/4282157675/jobs/7456077569#step:5:31)00086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
npm ERR! code 1
```

So it looks like `jf cli` is now succeeding! Give me a few minutes to work out why the next step is giving me that error. Thanks very much for the push on this. I really appreciate the pace at which you managed to get this fix out!

**Comment by rvodden** [comment]
@omerzi yeah, that was nothing to do with you. `jf cli` is working perfectly again for us now. Thank you very much for your expedience is resolving this!

**Comment by omerzi** [comment]
I'm glad to hear that @rvodden! Feel free to contact us if you have any further questions or need any assistance.
