### ISSUE TITLE
`jf c add --url=xxx --user=xxx --password=xxx` error 

### ISSUE THREAD

**Issue by axiangcoding** [jfrog/jfrog-cli#2153]
### Describe the bug

use script to get jfrog-cli, and execute it, it failed.
i believe the v2.41.0 cause the problem

### Current behavior

```go
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x130 pc=0xc8a3d6]
goroutine 1 [running]:
github.com/jfrog/jfrog-cli-core/v2/common/commands.(*ConfigCommand).resolveServerId(...)
	/root/go/pkg/mod/github.com/jfrog/jfrog-cli-core/v2@v2.41.0/common/commands/config.go:318
github.com/jfrog/jfrog-cli-core/v2/common/commands.(*ConfigCommand).prepareConfigurationData(0xc00031e[56](something-/jobs/765301#L56)8)
	/root/go/pkg/mod/github.com/jfrog/jfrog-cli-core/v2@v2.41.0/common/commands/config.go:287 +0x156
github.com/jfrog/jfrog-cli-core/v2/common/commands.(*ConfigCommand).config(0xc00031e568)
	/root/go/pkg/mod/github.com/jfrog/jfrog-cli-core/v2@v2.41.0/common/commands/config.go:162 +0x25
github.com/jfrog/jfrog-cli-core/v2/common/commands.(*ConfigCommand).Run(0xc00031e568)
	/root/go/pkg/mod/github.com/jfrog/jfrog-cli-core/v2@v2.41.0/common/commands/config.go:132 +0x271
github.com/jfrog/jfrog-cli/config.addOrEdit(0xc000276b00, 0x0)
	/var/jenkins_home/workspace/eco-system/release/jfrog-cli-release/temp/jfrog-cli/config/cli.go:139 +0x146
github.com/jfrog/jfrog-cli/config.addCmd(0xc000276b00)
	/var/jenkins_home/workspace/eco-system/release/jfrog-cli-release/temp/jfrog-cli/config/cli.go:94 +0x65
github.com/urfave/cli.HandleAction({0xf039a0?, 0x114c530?}, 0x3?)
	/root/go/pkg/mod/github.com/urfave/cli@v1.22.14/app.go:524 +0x50
github.com/urfave/cli.Command.Run({{0x1070340, 0x3}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x10bfc7e, 0x1c}, {0x0, ...}, ...}, ...)
	/root/go/pkg/mod/github.com/urfave/cli@v1.22.14/command.go:175 +0x67b
github.com/urfave/cli.(*App).RunAsSubcommand(0xc0001[62](something-/jobs/765301#L62)8c0, 0xc00027[68](something-/jobs/765301#L68)40)
	/root/go/pkg/mod/github.com/urfave/cli@v1.22.14/app.go:405 +0xe87
github.com/urfave/cli.Command.startApp({{0x1077c9c, 0x6}, {0x0, 0x0}, {0xc0003900e0, 0x1, 0x1}, {0x109809f, 0x10}, {0x0, ...}, ...}, ...)
	/root/go/pkg/mod/github.com/urfave/cli@v1.22.14/command.go:380 +0xb7f
github.com/urfave/cli.Command.Run({{0x1077c9c, 0x6}, {0x0, 0x0}, {0xc0003900e0, 0x1, 0x1}, {0x109809f, 0x10}, {0x0, ...}, ...}, ...)
	/root/go/pkg/mod/github.com/urfave/cli@v1.22.14/command.go:103 +0x845
github.com/urfave/cli.(*App).Run(0xc000162[70](something-/jobs/765301#L70)0, {0xc0000341e0, 0x6, 0x6})
	/root/go/pkg/mod/github.com/urfave/cli@v1.22.14/app.go:277 +0xb87
main.execMain()
	/var/jenkins_home/workspace/eco-system/release/jfrog-cli-release/temp/jfrog-cli/main.go:129 +0x353
main.main()
	/var/jenkins_home/workspace/eco-system/release/jfrog-cli-release/temp/jfrog-cli/main.go:[74](something-/jobs/765301#L74) +0x25
```

### Reproduction steps

1. get cli using `curl -fL https://install-cli.jfrog.io | sh`
2. execute ``jf c add --url=xxx --user=xxx --password=xxx``

### Expected behavior

everything works

### JFrog CLI version

v2.41.0

### Operating system type and version

alpine3

**Comment by RobiNino** [comment]
Hi @axiangcoding ,
Thanks for reporting this issue.
This was introduced in the latest version of JFrog CLI (2.46.0) that uses [jfrog-cli-core@v2.41.0](https://github.com/jfrog/jfrog-cli-core/releases/tag/v2.41.0).
I have created a [fix](https://github.com/jfrog/jfrog-cli-core/pull/915), and we will release a patch once it is merged.
Sorry for the inconvenience cause by this issue.
