### ISSUE TITLE
artifactory curl subcommand panics on help

### ISSUE THREAD

**Issue by dekimsey** [jfrog/jfrog-cli#2400]
### Describe the bug

Attempting to use the curl subcommand easily panics, including attempting to get help documentation.

### Current behavior

```
$ JFROG_CLI_LOG_LEVEL=DEBUG jf rt curl --help
15:15:29 [Debug] JFrog CLI version: 2.52.8
15:15:29 [Debug] OS/Arch: darwin/arm64
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x13a pc=0x104cabcb4]

goroutine 1 [running]:
github.com/jfrog/jfrog-cli-core/v2/utils/config.excludeRefreshableTokensFromDetails(...)
        github.com/jfrog/jfrog-cli-core/v2@v2.47.9/utils/config/config.go:81
github.com/jfrog/jfrog-cli-core/v2/utils/config.GetSpecificConfig({0x0, 0x0}, 0x1, 0x1)
        github.com/jfrog/jfrog-cli-core/v2@v2.47.9/utils/config/config.go:60 +0x274
github.com/jfrog/jfrog-cli-core/v2/common/commands.(*CurlCommand).GetServerDetails(0x140003b7000)
        github.com/jfrog/jfrog-cli-core/v2@v2.47.9/common/commands/curl.go:140 +0x16c
github.com/jfrog/jfrog-cli/artifactory.newRtCurlCommand(0x1400030e558?)
        github.com/jfrog/jfrog-cli/artifactory/cli.go:1837 +0x164
github.com/jfrog/jfrog-cli/artifactory.curlCmd(0x140003f26d0?)
        github.com/jfrog/jfrog-cli/artifactory/cli.go:1827 +0x2c
github.com/urfave/cli.HandleAction({0x1051ceae0?, 0x105352448?}, 0x4?)
        github.com/urfave/cli@v1.22.14/app.go:524 +0x58
github.com/urfave/cli.Command.Run({{0x104edd597, 0x4}, {0x0, 0x0}, {0x140002efc10, 0x1, 0x1}, {0x104f78360, 0x41}, {0x104f44bba, ...}, ...}, ...)
        github.com/urfave/cli@v1.22.14/command.go:175 +0x4f0
github.com/urfave/cli.(*App).RunAsSubcommand(0x140000fac40, 0x140002cc2c0)
        github.com/urfave/cli@v1.22.14/app.go:405 +0xa3c
github.com/urfave/cli.Command.startApp({{0x104edc72d, 0x2}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x104f12c06, 0x15}, {0x0, ...}, ...}, ...)
        github.com/urfave/cli@v1.22.14/command.go:380 +0x934
github.com/urfave/cli.Command.Run({{0x104edc72d, 0x2}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x104f12c06, 0x15}, {0x0, ...}, ...}, ...)
        github.com/urfave/cli@v1.22.14/command.go:103 +0x63c
github.com/urfave/cli.(*App).Run(0x140000faa80, {0x14000032080, 0x4, 0x4})
        github.com/urfave/cli@v1.22.14/app.go:277 +0x7c8
main.execMain()
        github.com/jfrog/jfrog-cli/main.go:130 +0x358
main.main()
        github.com/jfrog/jfrog-cli/main.go:75 +0x20

```

### JFrog CLI version

jf version 2.52.8

### Operating system type and version

OSX 13.6.1

**Comment by sverdlov93** [comment]
Hi @dekimsey 
Thanks for reporting this issue.
Our apologies for the inconvenience caused by this.
This [PR](https://github.com/jfrog/jfrog-cli/pull/2402) should fix it.
I will update this thread once the next release will be out.

**Comment by dekimsey** [comment]
Thank you, much appreciated!
