### ISSUE TITLE
"panic: runtime error: invalid memory address or nil pointer dereference" when running "jf audit" on yarn project

### ISSUE THREAD

**Issue by miki90014** [jfrog/jfrog-cli#2650]
### Describe the bug

When running "jf audit --dep-type prodOnly --npm=false --yarn=true --pnpm=false --fail=false --min-severity Critical --format simple-json" in Jenkins pipeline, we got the following error.

### Current behavior

```
07:04:30  + JFROG_CLI_LOG_LEVEL=ERROR
07:04:30  + CI=true
07:04:30  + jf audit --dep-type prodOnly --npm=false --yarn=true --pnpm=false --fail=false --min-severity Critical --format simple-json
07:04:36  panic: runtime error: invalid memory address or nil pointer dereference
07:04:36  [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xc75ef2]
07:04:36  
07:04:36  goroutine 1 [running]:
07:04:36  github.com/jfrog/build-info-go/build/utils.(*YarnDependency).Name(0xf8a2c0?)
07:04:36  	/root/go/pkg/mod/github.com/jfrog/build-info-go@v1.9.29/build/utils/yarn.go:353 +0x12
07:04:36  github.com/jfrog/jfrog-cli-security/commands/audit/sca/yarn.getXrayDependencyId(...)
07:04:36  	/root/go/pkg/mod/github.com/jfrog/jfrog-cli-security@v1.3.0/commands/audit/sca/yarn/yarn.go:218
07:04:36  github.com/jfrog/jfrog-cli-security/commands/audit/sca/yarn.parseYarnDependenciesMap(0xc00158e090, {0xc0005ba660, 0x12})
07:04:36  	/root/go/pkg/mod/github.com/jfrog/jfrog-cli-security@v1.3.0/commands/audit/sca/yarn/yarn.go:207 +0x448
07:04:36  github.com/jfrog/jfrog-cli-security/commands/audit/sca/yarn.BuildDependencyTree({0x1329a58, 0xc0001acb60})
07:04:36  	/root/go/pkg/mod/github.com/jfrog/jfrog-cli-security@v1.3.0/commands/audit/sca/yarn/yarn.go:76 +0x318
07:04:36  github.com/jfrog/jfrog-cli-security/commands/audit.GetTechDependencyTree({0x1329a58, 0xc0001acb60}, {0x10ca873, 0x4})
07:04:36  	/root/go/pkg/mod/github.com/jfrog/jfrog-cli-security@v1.3.0/commands/audit/scarunner.go:237 +0x39b
07:04:36  github.com/jfrog/jfrog-cli-security/commands/audit.executeScaScan(0xc0003c51e0, 0xc000493370, 0xc0015f0600)
07:04:36  	/root/go/pkg/mod/github.com/jfrog/jfrog-cli-security@v1.3.0/commands/audit/scarunner.go:122 +0x85
07:04:36  github.com/jfrog/jfrog-cli-security/commands/audit.runScaScan(0xc000493370, 0xc0005d6d80)
07:04:36  	/root/go/pkg/mod/github.com/jfrog/jfrog-cli-security@v1.3.0/commands/audit/scarunner.go:64 +0x48a
07:04:36  github.com/jfrog/jfrog-cli-security/commands/audit.RunAudit(0xc000493370)
07:04:36  	/root/go/pkg/mod/github.com/jfrog/jfrog-cli-security@v1.3.0/commands/audit/audit.go:205 +0x1ea
07:04:36  github.com/jfrog/jfrog-cli-security/commands/audit.(*AuditCommand).Run(0xc00019b8c0)
07:04:36  	/root/go/pkg/mod/github.com/jfrog/jfrog-cli-security@v1.3.0/commands/audit/audit.go:128 +0x1e7
07:04:36  github.com/jfrog/jfrog-cli-core/v2/common/commands.Exec({0x7f019050f338, 0xc00019b8c0})
07:04:36  	/root/go/pkg/mod/github.com/jfrog/jfrog-cli-core/v2@v2.53.1/common/commands/command.go:26 +0x96
07:04:36  github.com/jfrog/jfrog-cli-core/v2/common/progressbar.ExecWithProgress({0x131c648, 0xc00019b8c0})
07:04:36  	/root/go/pkg/mod/github.com/jfrog/jfrog-cli-core/v2@v2.53.1/common/progressbar/filesprogressbar.go:330 +0x125
07:04:36  github.com/jfrog/jfrog-cli-security/cli.AuditCmd(0xc0007005c0)
07:04:36  	/root/go/pkg/mod/github.com/jfrog/jfrog-cli-security@v1.3.0/cli/scancommands.go:334 +0x305
07:04:36  github.com/jfrog/jfrog-cli-core/v2/plugins/components.convertCommand.getActionFunc.func2(0xc0003f8688?)
07:04:36  	/root/go/pkg/mod/github.com/jfrog/jfrog-cli-core/v2@v2.53.1/plugins/components/conversionlayer.go:373 +0x4a
07:04:36  github.com/urfave/cli.HandleAction({0xf76e20?, 0xc000416a00?}, 0x5?)
07:04:36  	/root/go/pkg/mod/github.com/urfave/cli@v1.22.15/app.go:522 +0x9f
07:04:36  github.com/urfave/cli.Command.Run({{0x10cce52, 0x5}, {0x0, 0x0}, {0xc0004164a0, 0x1, 0x1}, {0x117551a, 0x62}, {0x0, ...}, ...}, ...)
07:04:36  	/root/go/pkg/mod/github.com/urfave/cli@v1.22.15/command.go:175 +0x685
07:04:36  github.com/urfave/cli.(*App).Run(0xc0003f6000, {0xc000000180, 0xc, 0xc})
07:04:36  	/root/go/pkg/mod/github.com/urfave/cli@v1.22.15/app.go:277 +0xb3b
07:04:36  main.execMain()
07:04:36  	/var/jenkins_home/workspace/eco-system/release/jfrog-cli-release/temp/jfrog-cli/main.go:134 +0x493
07:04:36  main.main()
07:04:36  	/var/jenkins_home/workspace/eco-system/release/jfrog-cli-release/temp/jfrog-cli/main.go:71 +0x1c
07:04:36  + [[ ! -s /home/jenkins/workspace/CSF/CAFOSS/building/scans/security-scan/scan_result.json ]]
07:04:36  + [[ true == \t\r\u\e ]]
07:04:36  + export YARN_ENABLE_IMMUTABLE_INSTALLS=false
07:04:36  + YARN_ENABLE_IMMUTABLE_INSTALLS=false
07:04:36  + JFROG_CLI_LOG_LEVEL=ERROR
07:04:36  + CI=true
07:04:36  + jf audit --dep-type prodOnly --npm=false --yarn=true --pnpm=false --fail=false --min-severity Critical --format simple-json
07:04:41  panic: runtime error: invalid memory address or nil pointer dereference
07:04:41  [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xc75ef2]
07:04:41  
07:04:41  goroutine 1 [running]:
07:04:41  github.com/jfrog/build-info-go/build/utils.(*YarnDependency).Name(0xf8a2c0?)
07:04:41  	/root/go/pkg/mod/github.com/jfrog/build-info-go@v1.9.29/build/utils/yarn.go:353 +0x12
07:04:41  github.com/jfrog/jfrog-cli-security/commands/audit/sca/yarn.getXrayDependencyId(...)
07:04:41  	/root/go/pkg/mod/github.com/jfrog/jfrog-cli-security@v1.3.0/commands/audit/sca/yarn/yarn.go:218
07:04:41  github.com/jfrog/jfrog-cli-security/commands/audit/sca/yarn.parseYarnDependenciesMap(0xc0002fe960, {0xc000eca0f0, 0x12})
07:04:41  	/root/go/pkg/mod/github.com/jfrog/jfrog-cli-security@v1.3.0/commands/audit/sca/yarn/yarn.go:207 +0x448
07:04:41  github.com/jfrog/jfrog-cli-security/commands/audit/sca/yarn.BuildDependencyTree({0x1329a58, 0xc00017a000})
07:04:41  	/root/go/pkg/mod/github.com/jfrog/jfrog-cli-security@v1.3.0/commands/audit/sca/yarn/yarn.go:76 +0x318
07:04:41  github.com/jfrog/jfrog-cli-security/commands/audit.GetTechDependencyTree({0x1329a58, 0xc00017a000}, {0x10ca873, 0x4})
07:04:41  	/root/go/pkg/mod/github.com/jfrog/jfrog-cli-security@v1.3.0/commands/audit/scarunner.go:237 +0x39b
07:04:41  github.com/jfrog/jfrog-cli-security/commands/audit.executeScaScan(0xc000312840, 0xc000597370, 0xc0003f9a40)
07:04:41  	/root/go/pkg/mod/github.com/jfrog/jfrog-cli-security@v1.3.0/commands/audit/scarunner.go:122 +0x85
07:04:41  github.com/jfrog/jfrog-cli-security/commands/audit.runScaScan(0xc000597370, 0xc000668cc0)
07:04:41  	/root/go/pkg/mod/github.com/jfrog/jfrog-cli-security@v1.3.0/commands/audit/scarunner.go:64 +0x48a
07:04:41  github.com/jfrog/jfrog-cli-security/commands/audit.RunAudit(0xc000597370)
07:04:41  	/root/go/pkg/mod/github.com/jfrog/jfrog-cli-security@v1.3.0/commands/audit/audit.go:205 +0x1ea
07:04:41  github.com/jfrog/jfrog-cli-security/commands/audit.(*AuditCommand).Run(0xc0001678c0)
07:04:41  	/root/go/pkg/mod/github.com/jfrog/jfrog-cli-security@v1.3.0/commands/audit/audit.go:128 +0x1e7
07:04:41  github.com/jfrog/jfrog-cli-core/v2/common/commands.Exec({0x7f7e1b20d3f8, 0xc0001678c0})
07:04:41  	/root/go/pkg/mod/github.com/jfrog/jfrog-cli-core/v2@v2.53.1/common/commands/command.go:26 +0x96
07:04:41  github.com/jfrog/jfrog-cli-core/v2/common/progressbar.ExecWithProgress({0x131c648, 0xc0001678c0})
07:04:41  	/root/go/pkg/mod/github.com/jfrog/jfrog-cli-core/v2@v2.53.1/common/progressbar/filesprogressbar.go:330 +0x125
07:04:41  github.com/jfrog/jfrog-cli-security/cli.AuditCmd(0xc0003d4000)
07:04:41  	/root/go/pkg/mod/github.com/jfrog/jfrog-cli-security@v1.3.0/cli/scancommands.go:334 +0x305
07:04:41  github.com/jfrog/jfrog-cli-core/v2/plugins/components.convertCommand.getActionFunc.func2(0xc00063a208?)
07:04:41  	/root/go/pkg/mod/github.com/jfrog/jfrog-cli-core/v2@v2.53.1/plugins/components/conversionlayer.go:373 +0x4a
07:04:41  github.com/urfave/cli.HandleAction({0xf76e20?, 0xc0003eaa00?}, 0x5?)
07:04:41  	/root/go/pkg/mod/github.com/urfave/cli@v1.22.15/app.go:522 +0x9f
07:04:41  github.com/urfave/cli.Command.Run({{0x10cce52, 0x5}, {0x0, 0x0}, {0xc0003ea4a0, 0x1, 0x1}, {0x117551a, 0x62}, {0x0, ...}, ...}, ...)
07:04:41  	/root/go/pkg/mod/github.com/urfave/cli@v1.22.15/command.go:175 +0x685
07:04:41  github.com/urfave/cli.(*App).Run(0xc000102fc0, {0xc00014e000, 0xc, 0xc})
07:04:41  	/root/go/pkg/mod/github.com/urfave/cli@v1.22.15/app.go:277 +0xb3b
07:04:41  main.execMain()
07:04:41  	/var/jenkins_home/workspace/eco-system/release/jfrog-cli-release/temp/jfrog-cli/main.go:134 +0x493
07:04:41  main.main()
07:04:41  	/var/jenkins_home/workspace/eco-system/release/jfrog-cli-release/temp/jfrog-cli/main.go:71 +0x1c
```

### Reproduction steps

We are using jf audit to scan this project: https://github.com/babel/babel/tree/v7.16.0/packages/babel-helper-get-function-arity
YARN_VERSION = 1.22.22
PNPM_VERSION = 9.1.0
NVM_VERSION = v0.39.7
NODE_VERSION = v20.11.1

### JFrog CLI version

2.59.1

### Operating system type and version

Jenkins using image of rocky8

**Comment by eyalbe4** [comment]
@miki90014,
To ensure the team seems this issue, will you be able to close this issue and open it under github.com/jfrog/jfrog-cli-security?
