### ISSUE TITLE
jfrog version 1.29.2 with DOCKER_BUILDKIT=1 causes `Could not find docker image in Artifactory, expecting image ID: sha256`

### ISSUE THREAD

**Issue by alexmnyc** [jfrog/jfrog-cli#519]
```
panic: Could not find docker image in Artifactory, expecting image ID: sha256:a55799516106ff38d532d4079e10065282c04a218c15d7aa816e6311bd0afd4d

goroutine 1 [running]:
github.com/jfrog/jfrog-cli-go/utils/cliutils.PanicOnError(0x8943300, 0xa640408, 0xa5493c8, 0x1)
	/var/lib/jenkins/workspace/EcoSystem/jfrog-cli-release/temp/jfrog-cli-go/utils/cliutils/utils.go:57 +0x42
github.com/jfrog/jfrog-cli-go/artifactory/utils/docker.(*buildInfoBuilder).getImageLayersFromArtifactory(0xa8c8180, 0xa668710, 0x8117beb, 0x8117a0c)
	/var/lib/jenkins/workspace/EcoSystem/jfrog-cli-release/temp/jfrog-cli-go/artifactory/utils/docker/buildinfo.go:126 +0x5f1
github.com/jfrog/jfrog-cli-go/artifactory/utils/docker.(*buildInfoBuilder).updateArtifactsAndDependencies(0xa8c8180, 0xa4eaf50, 0x47)
	/var/lib/jenkins/workspace/EcoSystem/jfrog-cli-release/temp/jfrog-cli-go/artifactory/utils/docker/buildinfo.go:84 +0x2f
github.com/jfrog/jfrog-cli-go/artifactory/utils/docker.(*buildInfoBuilder).Build(0xa8c8180, 0x0, 0x0, 0x0, 0x0, 0x0)
	/var/lib/jenkins/workspace/EcoSystem/jfrog-cli-release/temp/jfrog-cli-go/artifactory/utils/docker/buildinfo.go:65 +0x62
github.com/jfrog/jfrog-cli-go/artifactory/commands/docker.(*DockerPushCommand).Run(0xa5724e0, 0x8835fa0, 0x894a4e0)
	/var/lib/jenkins/workspace/EcoSystem/jfrog-cli-release/temp/jfrog-cli-go/artifactory/commands/docker/push.go:69 +0x26e
github.com/jfrog/jfrog-cli-go/artifactory/commands.Exec(0x894a4e0, 0xa5724e0, 0x0, 0x0)
	/var/lib/jenkins/workspace/EcoSystem/jfrog-cli-release/temp/jfrog-cli-go/artifactory/commands/command.go:26 +0x71
github.com/jfrog/jfrog-cli-go/artifactory.dockerPushCmd(0xa4a0580, 0x81547c1, 0x87fa8c3)
	/var/lib/jenkins/workspace/EcoSystem/jfrog-cli-release/temp/jfrog-cli-go/artifactory/cli.go:1530 +0x193
github.com/jfrog/jfrog-cli-go/artifactory.GetCommands.func25(0xa4a0580, 0x0, 0xa4a0580)
	/var/lib/jenkins/workspace/EcoSystem/jfrog-cli-release/temp/jfrog-cli-go/artifactory/cli.go:393 +0x21
github.com/codegangsta/cli.HandleAction(0x871cfe0, 0x8835f44, 0xa4a0580, 0xa570900, 0x0)
	/var/lib/jenkins/go/pkg/mod/github.com/codegangsta/cli@v1.20.0/app.go:490 +0xa2
github.com/codegangsta/cli.Command.Run(0x87fe253, 0xb, 0x0, 0x0, 0xa562210, 0x1, 0x1, 0x87fe857, 0xc, 0x8826985, ...)
	/var/lib/jenkins/go/pkg/mod/github.com/codegangsta/cli@v1.20.0/command.go:210 +0x89c
github.com/codegangsta/cli.(*App).RunAsSubcommand(0xa4dce00, 0xa4a0420, 0x0, 0x0)
	/var/lib/jenkins/go/pkg/mod/github.com/codegangsta/cli@v1.20.0/app.go:379 +0x6c2
github.com/codegangsta/cli.Command.startApp(0x87f9e9c, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8804073, 0x14, 0x0, ...)
	/var/lib/jenkins/go/pkg/mod/github.com/codegangsta/cli@v1.20.0/command.go:298 +0x69b
github.com/codegangsta/cli.Command.Run(0x87f9e9c, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8804073, 0x14, 0x0, ...)
	/var/lib/jenkins/go/pkg/mod/github.com/codegangsta/cli@v1.20.0/command.go:98 +0xf5e
github.com/codegangsta/cli.(*App).Run(0xa4dcc40, 0xa4840c0, 0x7, 0x8, 0x0, 0x0)
	/var/lib/jenkins/go/pkg/mod/github.com/codegangsta/cli@v1.20.0/app.go:255 +0x56a
main.execMain(0x869d328, 0xa42e370)
	/var/lib/jenkins/workspace/EcoSystem/jfrog-cli-release/temp/jfrog-cli-go/main.go:90 +0x1f8
main.main()
	/var/lib/jenkins/workspace/EcoSystem/jfrog-cli-release/temp/jfrog-cli-go/main.go:72 +0x1f
```

Similar https://github.com/jfrog/jfrog-cli/issues/160

**Comment by barbelity** [comment]
@alexmnyc, the issue in #160 turned out to be a bad JFrog CLI command.
Can you please share the command you are running?

**Comment by eyalbe4** [comment]
@alexmnyc,
Is this issue still relevant?

**Comment by ppiotrow** [comment]
I have the same error after start building images with `DOCKER_BUILDKIT=1`

**Comment by Or-Gabay** [comment]
@alexmnyc , @ppiotrow , I was able to build my docker image with buildkit and publish it to Artifactory as well.
Could you please share with us:
1. Steps to reproduce the behavior
2. A clear and concise description of what you expected to happen.
3. JFrog CLI version:
4. Artifactory Version

**Comment by shuvadipc** [comment]
No response, outdated.
