### ISSUE TITLE
Docker push fails in v1.35.4

### ISSUE THREAD

**Issue by michal-dragon** [jfrog/jfrog-cli#693]
**Describe the bug**
After the release of version 1.35.4, we are experiencing crashes when running `jfrog rt dp`
We are using the `circleci/artifactory@1.0.0` orb and our task fails on `artifactory/docker-publish`. The command being executed is:
```
jfrog rt dp ${DOCKER_REGISTRY}/${PROJECT_NAME}:${CIRCLE_BUILD_NUM} docker-apps --build-name=${CIRCLE_PROJECT_REPONAME} --build-number=${CIRCLE_BUILD_NUM}
```

The rerun of a previously successful task (2 days ago) now also fails as the task installs the latest version of JFrog CLI.

**To Reproduce**
For some docker images, the `docker-push` command still works fine, but for others, it fails consistently.

**Versions**
- JFrog CLI version: 1.35.4
- JFrog CLI operating system:
- Artifactory Version:

**Additional context**

Stack trace:
```
panic: runtime error: index out of range [48] with length 48

goroutine 1 [running]:
github.com/jfrog/jfrog-cli/artifactory/utils/docker.(*buildInfoBuilder).handlePush(0xc00054e000, 0xda0cc3, 0xd, 0xd9b88e, 0x4, 0xc00041a3c0, 0xc000411d10, 0x48, 0x0, 0x0, ...)
	/var/lib/jenkins/workspace/EcoSystem/jfrog-cli-release/temp/jfrog-cli/artifactory/utils/docker/buildinfo.go:202 +0xcdb
github.com/jfrog/jfrog-cli/artifactory/utils/docker.(*buildInfoBuilder).updateArtifactsAndDependencies(0xc00054e000, 0xc000410140, 0x47)
	/var/lib/jenkins/workspace/EcoSystem/jfrog-cli-release/temp/jfrog-cli/artifactory/utils/docker/buildinfo.go:111 +0x47d
github.com/jfrog/jfrog-cli/artifactory/utils/docker.(*buildInfoBuilder).Build(0xc00054e000, 0x0, 0x0, 0xb, 0x7ffcf5f4ebd8, 0x16)
	/var/lib/jenkins/workspace/EcoSystem/jfrog-cli-release/temp/jfrog-cli/artifactory/utils/docker/buildinfo.go:76 +0x77
github.com/jfrog/jfrog-cli/artifactory/commands/docker.(*DockerPushCommand).Run(0xc00023eb80, 0xddf538, 0xf100a0)
	/var/lib/jenkins/workspace/EcoSystem/jfrog-cli-release/temp/jfrog-cli/artifactory/commands/docker/push.go:79 +0x2a3
github.com/jfrog/jfrog-cli/artifactory/commands.Exec(0xf100a0, 0xc00023eb80, 0x0, 0x0)
	/var/lib/jenkins/workspace/EcoSystem/jfrog-cli-release/temp/jfrog-cli/artifactory/commands/command.go:26 +0x89
github.com/jfrog/jfrog-cli/artifactory.dockerPushCmd(0xc000146c60, 0xc0001c4ac0, 0x547705)
	/var/lib/jenkins/workspace/EcoSystem/jfrog-cli-release/temp/jfrog-cli/artifactory/cli.go:2114 +0x1cf
github.com/jfrog/jfrog-cli/artifactory.GetCommands.func25(0xc000146c60, 0x100, 0xc000146c60)
	/var/lib/jenkins/workspace/EcoSystem/jfrog-cli-release/temp/jfrog-cli/artifactory/cli.go:418 +0x2b
github.com/codegangsta/cli.HandleAction(0xc70640, 0xddf400, 0xc000146c60, 0xc00013db00, 0x0)
	/var/lib/jenkins/go/pkg/mod/github.com/codegangsta/cli@v1.20.0/app.go:490 +0xc8
github.com/codegangsta/cli.Command.Run(0xd9f65e, 0xb, 0x0, 0x0, 0xc0001b5b90, 0x1, 0x1, 0xd9fccf, 0xc, 0xdcbe86, ...)
	/var/lib/jenkins/go/pkg/mod/github.com/codegangsta/cli@v1.20.0/command.go:210 +0x9e8
github.com/codegangsta/cli.(*App).RunAsSubcommand(0xc0001df1e0, 0xc0001469a0, 0x0, 0x0)
	/var/lib/jenkins/go/pkg/mod/github.com/codegangsta/cli@v1.20.0/app.go:379 +0x88b
github.com/codegangsta/cli.Command.startApp(0xd9ad6d, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0xda5d90, 0x14, 0x0, ...)
	/var/lib/jenkins/go/pkg/mod/github.com/codegangsta/cli@v1.20.0/command.go:298 +0x81a
github.com/codegangsta/cli.Command.Run(0xd9ad6d, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0xda5d90, 0x14, 0x0, ...)
	/var/lib/jenkins/go/pkg/mod/github.com/codegangsta/cli@v1.20.0/command.go:98 +0x1219
github.com/codegangsta/cli.(*App).Run(0xc0001ded00, 0xc000140000, 0x7, 0x7, 0x0, 0x0)
	/var/lib/jenkins/go/pkg/mod/github.com/codegangsta/cli@v1.20.0/app.go:255 +0x741
main.execMain(0xc551e0, 0xc000114058)
	/var/lib/jenkins/workspace/EcoSystem/jfrog-cli-release/temp/jfrog-cli/main.go:89 +0x1ab
main.main()
	/var/lib/jenkins/workspace/EcoSystem/jfrog-cli-release/temp/jfrog-cli/main.go:71 +0x27
```

**Comment by michal-dragon** [comment]
It looks like this was caused by https://github.com/jfrog/jfrog-cli/pull/685.
The function `removeDuplicateDockerLayers` removes a layer from `imageManifest.Layers` but the `totalLayers`count used in the loop condition is calculated from `configurationLayer`.

The previous successful build contained 52 digests in the output and out of those 2 values appeared twice in the output:
```
[Info] [Thread 1] Setting properties on: docker-apps/${PROJECT_NAME}/108/sha256__3b47c133b222af6ee65e00394afec5f6c794d2bbc00c350f26dc92858463392c
[Info] [Thread 2] Setting properties on: docker-apps/${PROJECT_NAME}/108/sha256__3b47c133b222af6ee65e00394afec5f6c794d2bbc00c350f26dc92858463392c
[Info] [Thread 1] Setting properties on: docker-apps/${PROJECT_NAME}/108/sha256__adefe4179834c1ca398c198bbee39905888ba45ecb51f1c29f910128bbb30f65
[Info] [Thread 0] Setting properties on: docker-apps/${PROJECT_NAME}/108/sha256__adefe4179834c1ca398c198bbee39905888ba45ecb51f1c29f910128bbb30f65
```

**Comment by Or-Gabay** [comment]
@michal-dragon, we released JFrog CLI v1.35.5 to resolve this issue.
Feel free to upgrade - We'll appreciate your feedback for that!

**Comment by eyalbe4** [comment]
https://github.com/jfrog/jfrog-cli/pull/694 includes the fix.

**Comment by michal-dragon** [comment]
Thanks for the fast response, v1.35.5 fixes the issue 🎉
