### ISSUE TITLE
"jfrog rt dotnet restore" produces panic

### ISSUE THREAD

**Issue by kirchsth** [jfrog/jfrog-cli#996]
**To Reproduce**

I installed last "jfrog-cli v1.45.0 [Approved]" via "choco upgrade jfrog-cli" (Windows 10) 
and started it (in a folder with a "Visual Studio 2019 solution") with following command:
```
jfrog rt dotnet restore
```
it prompts
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0xd12826]

goroutine 1 [running]:
github.com/jfrog/jfrog-cli/artifactory.dotnetCmd(0xc0001474a0, 0xc00011ca90, 0x8aa90c)
        /var/jenkins_home/workspace/eco-system/release/jfrog-cli-release/temp/jfrog-cli/artifactory/cli.go:1505 +0x416
github.com/jfrog/jfrog-cli/artifactory.GetCommands.func40(0xc0001474a0, 0x0, 0xc0001474a0)
        /var/jenkins_home/workspace/eco-system/release/jfrog-cli-release/temp/jfrog-cli/artifactory/cli.go:636 +0x32
github.com/codegangsta/cli.HandleAction(0xdece20, 0xf91158, 0xc0001474a0, 0xc00006d000, 0x0)
        /root/go/pkg/mod/github.com/codegangsta/cli@v1.20.0/app.go:490 +0xcf
github.com/codegangsta/cli.Command.Run(0xf43856, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xf762ae, ...)
        /root/go/pkg/mod/github.com/codegangsta/cli@v1.20.0/command.go:210 +0x9ef
github.com/codegangsta/cli.(*App).RunAsSubcommand(0xc0001c6d00, 0xc0001471e0, 0x0, 0x0)
        /root/go/pkg/mod/github.com/codegangsta/cli@v1.20.0/app.go:379 +0x892
github.com/codegangsta/cli.Command.startApp(0xf41733, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /root/go/pkg/mod/github.com/codegangsta/cli@v1.20.0/command.go:298 +0x821
github.com/codegangsta/cli.Command.Run(0xf41733, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /root/go/pkg/mod/github.com/codegangsta/cli@v1.20.0/command.go:98 +0x1220
github.com/codegangsta/cli.(*App).Run(0xc0001c6b60, 0xc00003e080, 0x4, 0x4, 0x0, 0x0)
        /root/go/pkg/mod/github.com/codegangsta/cli@v1.20.0/app.go:255 +0x748
main.execMain(0xc00011df78, 0x405ee6)
        /var/jenkins_home/workspace/eco-system/release/jfrog-cli-release/temp/jfrog-cli/main.go:102 +0x1b2
main.main()
        /var/jenkins_home/workspace/eco-system/release/jfrog-cli-release/temp/jfrog-cli/main.go:81 +0x32
```

The same can be reproduced in any folder

**Expected behavior**
a) all (.netcore) nuget packages are restored
b) or based on source check I should see the warning that `jfrog rt dotnet-config` is missing

**Versions**
- JFrog CLI version:  1.45.0
- JFrog CLI operating system: Windows 10
- Artifactory Version:

**Additional context**
-

**Comment by Or-Geva** [comment]
@kirchsth, thanks for reporting this issue. I submitted a [PR](https://github.com/jfrog/jfrog-cli/pull/998) that includes a fix for this issue.
We will release this fix in a few hours.

**Comment by kirchsth** [comment]
Hi @Or-Geva, thank you for the fast fix.
BR Helmut

**Comment by eyalbe4** [comment]
@kirchsth,
JFrog CLI 1.45.1 is released and include this fix.

**Comment by eyalbe4** [comment]
@kirchsth - 
I'm closing this issue for now, but please let us know if you need further assistance with this.
